threadPool:
  core: 4
  max: 64
  queue: 5000
#mode: JDCB,HTTP
mode: JDCB
enable: true
url: "jdbc:TAOS://localhost:6030/?timezone=Asia/Chongqing"
username: root
password: taosdata
database: mqtt
table: 'mqtt_payload'
# RAW origin ; BASE64 base64 encoded; HEX hex;
payloadCoder: BASE64
# maximum wait milliseconds for connection (connect/read) timeout
timeout: 10000
# maximum number of connection in the pool
maxConnections: 10
