threadPool:
  core: 4
  max: 64
  queue: 5000
#mode: JDBC, HTTP
mode: JDBC
url: "jdbc:TAOS://localhost:6030/?timezone=Asia/Chongqing"
username: root
password: taosdata
database: mqtt
table:
  name: 'mqtt_payload'
  # if table mode is SUPER_TABLE, tableNameMode is required
  # The available modes are: USERNAME, CLIENT_ID
  use: USERNAME
  # FIXED replace none number or letter to '_'
  # MD5 hash to md5
  format: FIXED


# RAW origin ; BASE64 base64 encoded; HEX hex;
payloadCoder: BASE64
# maximum wait milliseconds for connection (connect/read) timeout
timeout: 10000
# maximum number of connection in the pool
maxConnections: 10


